apiVersion: v1
kind: Pod
metadata:
  name: my-ok-pod
  labels:
    app:
spec:
  containers:
    - name: response-ok
      image: maximchik40/response-ok-myapp
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
  restartPolicy: Always
