apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
  labels:
    app: kuber-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: kuber-deployment_(template_metadata_name)
      labels:
        env: dev-label-name
    spec:
      containers:
        - name: response-ok
          image: maximchik40/service-lab4:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: kuber-secret
                key: dbuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kuber-secret
                key: dbpass
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: kuber-configmap
                key: dburl
      restartPolicy: Always
  selector:
    matchLabels:
      env: dev-label-name
